### ISSUE TITLE
Failed load on client startup - button missing

### ISSUE THREAD

**Issue by kreezxil** [Axieum/AuthMe#1]
![image](https://user-images.githubusercontent.com/3880072/73297393-20a6e400-41d1-11ea-924a-df3b7c1df78f.png)

authme: 1.14_1.15-1.1.0
mc: 1.15.2
forge: 31.0.1

latest.log as there is no crash: https://gist.github.com/kreezxil/28d1b7229417fc1b778956c4977369f6

**Comment by Axieum** [comment]
Thanks for reporting this, I am yet to test with the new `1.15.2` release, but from the looks of things, Forge must have removed their custom button. I have made a release here to use vanilla Minecraft's button.

https://github.com/Axieum/AuthMe/releases/tag/v1.14_1.15-1.1.1
