### ISSUE TITLE
AuthMe is not compatible with Microsoft Accounts 

### ISSUE THREAD

**Issue by EricKilla** [axieum/authme#12]
I am not able to use AuthMe to log into a Microsoft account. New accounts are currently being forced to use Microsoft accounts. AuthMe does still work with my Mojang accounts.

**Comment by Axieum** [comment]
Thanks for the heads up! I'll try find some time to look into this soon.

I am also happy if anyone would like to contribute a PR 😊

**Comment by Andrews54757** [comment]
Might be useful:

[Example code](https://github.com/MiniDigger/MiniLauncher/blob/master/launcher/src/main/java/me/minidigger/minecraftlauncher/launcher/gui/MsaFragmentController.java) from MiniLauncher. Protocol documentation on [wiki.vg](https://wiki.vg/Microsoft_Authentication_Scheme)

**Comment by boasbakker** [comment]
MultiMC also has it
Migration has also started, so it is even more important

**Comment by Alexxiconify** [comment]
GDLauncher has it so what you have to do is launch a login to Microsoft directly which sucks as it places a pop up add but if it allows you to add a save password feature like the ingame launcher has currently as you can save it in a mod folder (encrypted of course).

**Comment by Alexxiconify** [comment]
I think you have to have them write in their info and maybe a config setting to change it to Microsoft account &/or have a button to toggle from Mojang to Microsoft login. Once they place in the login credentials you then tunnel process it through to Microsoft Minecraft login and get the session Id like you normally do using it. So you have to launch some custom https code.

**Comment by RealHypnoticOcelot** [comment]
i would also like this feature, invalid session is really annoying

**Comment by axieum** [comment]
I appreciate your interest in this. I finally got my invite to migrate my account - so I'll try to pick this up soon!

My focus had been on my latest project [Minecord](https://github.com/axieum/minecord) which is nearing a release very soon.

**Comment by axieum** [comment]
I am working on this issue, and am aiming to have something ready for 1.18!

Sneak-peak:

![image](https://user-images.githubusercontent.com/7577851/139517197-71e1aeb4-4f63-4a82-a1fd-054802c24f6b.png)

**Comment by RealHypnoticOcelot** [comment]
looks awesome!!!!

**Comment by axieum** [comment]
Fixed cb72cdb6e37a01cd20a581a107b3fbe96ffd9c70
