### ISSUE TITLE
mod info

### ISSUE THREAD

**Issue by 0142929** [axieum/AuthMe#17]
[31May2021 18:39:07.040] [main/WARN] [net.minecraftforge.fml.server.ServerModLoader/LOADING]: File authme-1.16.3-1.4.0.jar is a Fabric mod and cannot be loaded

it would be very cool if the mod description was info that it is not forge mod!
thanks.

**Comment by axieum** [comment]
The mod itself on CurseForge is tagged with `Fabric`, and the jars are also tagged for the `Fabric` platform.

**Comment by Gunner76th** [comment]
@axieum Looking over your Curseforge page for this mod, both on the Description page as well as the Downloads page, the ONLY indication that this might be a fabric mod is in your Change log section for the file where it references "Update fabric.mod.json" 

There is no notification anywhere on the Description page, and no indicator page that this is in fact a fabric mod. I wasn't able to definitively determine that this was in fact a fabric only mod until I came here to GitHub where you explicitly state this is "It is a client-side only mod, built on the Fabric mod loader and is available for modern versions of Minecraft Java Edition." 

Failure to post that this is a Fabric mod on the description page, or putting "Fabric" in the name field for the Mod name (Auth Me - Fabric), or some other means of clearly and explicitly stating that this is now a fabric only mod is not only poor management, but can be considered false representation. False representation could be grounds for Curseforge to pull your mod from the listing until the description is clarified to state that it is only for Farbic in 1.17.1 and newer. Please update your Description page to state that this is a Fabric only mod, something which almost every other mod author has done so far.

**Comment by axieum** [comment]
Please refer to https://github.com/axieum/authme/issues/17#issuecomment-855323841.

I am not allowed to include keywords "Fabric" or "Forge" in the mod title, I have gotten in trouble for this in the past.

Please direct this feedback to the CurseForge platform, they are under new ownership (Overwolf) and would be more than happy to receive this feedback regarding incorporating mod loaders directly into their mod listing UI. 😊

**Comment by DoctorMage** [comment]
> 
> 
> Please refer to [#17 (comment)](https://github.com/axieum/authme/issues/17#issuecomment-855323841).
> 
> I am not allowed to include keywords "Fabric" or "Forge" in the mod title, I have gotten in trouble for this in the past.
> 
> Please direct this feedback to the CurseForge platform, they are under new ownership (Overwolf) and would be more than happy to receive this feedback regarding incorporating mod loaders directly into their mod listing UI. 😊

If cf has an issue with having Fabric or forge in the mod title then show them these mods unless theirs a reason specifcally its not allowed for what your mod does

https://www.curseforge.com/minecraft/mc-mods/ftb-backups-forge
https://www.curseforge.com/minecraft/mc-mods/randompatches-forge
https://www.curseforge.com/minecraft/mc-mods/curios
https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-fabric
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric
https://www.curseforge.com/minecraft/mc-mods/cloth-config
https://www.curseforge.com/minecraft/mc-mods/light-overlay
https://www.curseforge.com/minecraft/mc-mods/hardcore-questing-mode
https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric
https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc
https://www.curseforge.com/minecraft/mc-mods/falling-tree
