### ISSUE TITLE
Password is logged in the game logs

### ISSUE THREAD

**Issue by Andrews54757** [Axieum/AuthMe#3]
https://github.com/Axieum/AuthMe/blob/2a37d86eaed42e51abb50ad7b154a83ea163a703/src/main/java/me/axieum/mcmod/authme/gui/AuthScreen.java#L167

**Comment by Axieum** [comment]
Oh my god! I can't believe I accidentally left this in there... 

Thank you so much for letting me know about this, I'll fix it up immediately and delete other versions from CurseForge!
