### ISSUE TITLE
Can't log in on 1.16.5 with a Microsoft account

### ISSUE THREAD

**Issue by KingsMMA** [axieum/authme#30]
### Expected behavior

You should be able to log in with a microsoft account

### Observed/actual behavior

You cannot log in with a microsoft account

### Steps/models to reproduce

1) Click the log in button

### Version

1.16.3-1.4.0

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Wolfy8198** [comment]
I've noticed this as well, and my Minecraft Origins server is on 1.16.5. I would love an update for the 1.16.5 version of the mod that adds compatibility with Microsoft accounts.

**Comment by axieum** [comment]
I'll try to backport the latest changes to 1.16, may take me a while as 1.17 & 1.18 use Java 16 and Java 17 respectively - and I'm unsure of what new features I've used since Java 8 ⏳

**Comment by axieum** [comment]
Find the binaries here https://github.com/axieum/authme/releases/tag/v2.1.0
