### ISSUE TITLE
[BUG] Server doesn't see plugin

### ISSUE THREAD

**Issue by JustBooom** [axieum/authme#32]
### Expected behavior

I had authme plugin on my 1.16.5 spigot server, and everything was great, but when i made the same one on 1.18 and downloaded authme for 1.18 (authme-mc1.18-2.1.0.jar), server just don't see it. The problem is not in server, because my other 7 plugins work great.

### Observed/actual behavior

![image](https://user-images.githubusercontent.com/83309505/145716081-96305c01-2421-4734-9308-5f05112ee080.png)
![image](https://user-images.githubusercontent.com/83309505/145716103-5a2b1cb0-ed7c-429d-a79d-50ca431ac1bd.png)

### Steps/models to reproduce

i made a server following this guide https://www.spigotmc.org/wiki/buildtools/
and tried authme from github and curseforge

### Version

Minecraft spigot 1.18
authme-mc1.18-2.1.0.jar

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [x] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by JustBooom** [comment]
oh wait, it's not a plugin, it's mod lol. But still, will there be authme plugin for 1.18?

**Comment by axieum** [comment]
Hi @JustBooom,

Sorry for the inconvenience. Auth Me is a mod to log in to other Minecraft accounts without restarting the game. It is all client-sided. I have heard of a similar named mod/plugin for Spigot, but I don't believe that is available on CurseForge? So I'm unsure of where you could find that plugin.

Thanks,
Ax.
