### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by devendrapoonia** [axieum/authme#39]
### Expected behavior

Game should start normally with AuthMe

### Observed/actual behavior

AuthMe is crashing the game.

### Steps/models to reproduce

Put AuthMe in mods folder and start the game.

### Version

2,2,0

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

Crash Report - https://crashy.net/bQGjNXay8Hu4ZDX7Y83M

**Comment by axieum** [comment]
Closed in #42
