### ISSUE TITLE
AuthMe 1.16 does not load

### ISSUE THREAD

**Issue by caribhunt** [Axieum/AuthMe#5]
When starting a server I get an error in a console and the plugin does not start after it. Everiything was working on versions before
https://pastebin.com/dAdPdMXD
Downloaded https://github.com/Axieum/AuthMe/releases/download/v1.2.1/authme-1.16.1-1.2.1.jar

**Comment by Axieum** [comment]
I'm not sure how this was working before, but this is a client-side only mod built for the Fabric mod loader. It is not mentioned anywhere that this is built for Bukkit or servers for that matter.

If you think I could improve the mod description in anyway to reflect this, please let me know.
