### ISSUE TITLE
Unable to join servers with chat verification turned on

### ISSUE THREAD

**Issue by jSdCool** [axieum/authme#60]
### Expected behavior

when re validating the session everything needed to jaoin a serv er is updated and works

### Observed/actual behavior

after getting an invalid session I used this mod to make my session valid again however when I then tried to join a server I got the message 'Expired profile public key. Check that your system time is synchronized and try restarting your game' and was prevented from joining the server

### Steps/models to reproduce

1) get an invalid session 
2) use the mod to make your cession valid
3) try to join a server with the default chat validation settings
![2022-10-02_11 51 50](https://user-images.githubusercontent.com/37940266/193463263-9d8b6e98-c146-450c-9202-480bd3dbe5b7.png)

### Version

1.19-4.1.0
minecraft: 1.19.2

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by jSdCool** [comment]
[2022-10-02-1.log](https://github.com/axieum/authme/files/9692931/2022-10-02-1.log)
log file if that will help

**Comment by axieum** [comment]
Thanks for this, I'll try reproduce it soon by joining a server with chat verification turned on. I suspect the new chat message signing needs a new key generating.

**Comment by axieum** [comment]
I've found this related error message aswell: 
![image](https://user-images.githubusercontent.com/7577851/194703833-722c59cf-2164-4053-baff-3ca22245dc46.png)
