### ISSUE TITLE
Crashes on 1.16.2

### ISSUE THREAD

**Issue by Neubulae** [Axieum/AuthMe#7]
1.Click multiplayer
2.

**Comment by Axieum** [comment]
Lol. I went to rebuild it on 1.16.2 the other day but Fabric wasn't playing nice, it wasn't ready with Biomes or something. There will need to be a new version for 1.16.2 built as they moved around a few of the realms classes, more notably the realms disconnection screen.

All is ready, just waiting on Fabric to work with 1.16.2.

**Comment by Axieum** [comment]
Fixed in commit fb2a0d2, please see release [v1.3.1](/Axieum/AuthMe/releases/tag/v1.3.1).
