### ISSUE TITLE
invalid profile public key

### ISSUE THREAD

**Issue by jSdCool** [axieum/authme#73]
### Expected behavior

chat message send normally 

### Observed/actual behavior

message does not send and a message appears say that I have an invalid profile public key

### Steps/models to reproduce

open 1.19.3 with this mod
use this mod to re login to your account
join a server with chat reporting
try to send a message

### Version

5.0.0

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

in 1.19.3 a change was made to auto refresh the profile public key to prevent this message from appearing
the issue is prbly related to this

**Comment by axieum** [comment]
Hi 👋

Happy new year, I'm currently away and will be able to take a look in the coming weeks.

Here are the lines of code I suspect are at fault, but I can't do any debugging yet:

https://github.com/axieum/authme/blob/7ef38e0aae5833f5260ae6c2789a03b2bc4fbba8/src/main/java/me/axieum/mcmod/authme/api/util/SessionUtils.java#L87-L90

Thanks for your patience.
