### ISSUE TITLE
suggestion: button is movable

### ISSUE THREAD

**Issue by minecraftDigi101** [Axieum/AuthMe#8]
I have many client-side mods, and I personally like the skin-swapper. and when I found this mod I was like "omg this is awesome!"
and I went to test it and what I found was the buttons overlapped and it was very annoying

if you were able to make config and make it so you can move it anywhere on the screen(in the multiplayer tab) so basically I can actually press it without it pressing the skin swapper button too.

here, I'm going to send you a screenshot: 
![Minecraft 1 16 3 10_1_2020 6_31_24 PM](https://user-images.githubusercontent.com/66649143/94879269-9cb69300-0414-11eb-97cc-86754c8dfa1b.png) and hopefully you can see for yourself

**Comment by Axieum** [comment]
Hi @minecraftDigi101,

Thanks for the feedback, I'll be sure to take a look into this when I get some spare time.

If you'd like a solution in the interim, you can fiddle with the first two X and Y numbers here:

https://github.com/Axieum/AuthMe/blob/ad15e9473177b5545c327a3d9b01283d1c973ed4/src/main/java/me/axieum/mcmod/authme/mixin/MultiplayerScreenMixin.java#L32-L45

..and run `./gradlew build` and fetch your mod jar from `build/lib/`.

I would do this for you, but in the context of a mod that handles passwords (and you can't hash check the source with the build), it's best that you compile this yourself.

I will look into making the button position configurable.

Thanks,
Axieum.
