### ISSUE TITLE
Disconnected screen crashes the game when adding the re-login button

### ISSUE THREAD

**Issue by AnAwesomGuy** [axieum/authme#87]
### Expected behavior

show the disconnected screen

### Observed/actual behavior

game crashed and showed "saving world" for a split second

### Steps/models to reproduce

join a server
get kicked
see that the game crashes

### Version

7.0.0

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

[crash-2023-06-10_11.18.28-client.txt](https://github.com/axieum/authme/files/11711414/crash-2023-06-10_11.18.28-client.txt)
looks like [this](https://github.com/axieum/authme/blob/main/src/main/java/me/axieum/mcmod/authme/mixin/DisconnectedScreenMixin.java#L44-L69) mixin is crashing
it says that a TextWidget cannot be cast to a ButtonWidget in the DisconnectedScreen,

**Comment by AnAwesomGuy** [comment]
also, it _does_ show "Adding auth button to the disconnected screen"

**Comment by axieum** [comment]
Thanks for reporting this @AnAwesomGuy. Please find the working version here: https://modrinth.com/mod/auth-me/version/7.0.1+1.20

**Comment by AnAwesomGuy** [comment]
wait that was actually just fixable by changing a _single_ number?

**Comment by axieum** [comment]
Yeah, it looks like they added a couple labels before the buttons on that screen. Ideally, could iterate through the elements for the first `ButtonWidget` but this was the quickest fix.
