### ISSUE TITLE
Modrinth description has incorrect HTML in `<img>` tag

### ISSUE THREAD

**Issue by James103** [axieum/authme#96]
### Expected behavior

In the Modrinth description, there should be a GIF showing some of the possibilities of the Auth Me mod.

The relevant raw HTML should be as follows:
```
<img alt="Auth Me Demo" src="https://github.com/axieum/authme/raw/main/demo.gif" width="50%" align="right">
```

### Observed/actual behavior

The above HTML is incorrectly typed and displays as is:
```
<img alt="Auth Me Demo" src="https://github.com/axieum/authme/raw/main/demo.gif" width="50%" align="right>
```
(missing double quotes `"` near the end).

### Steps/models to reproduce

Check the Modrinth description for the mod: https://modrinth.com/mod/auth-me

### Version

`authme-7.0.2+1.20.jar` (assumed latest)
Issue is with mod description, accessed 7 July 2023.

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by axieum** [comment]
Thank you for pointing this out. I've gone ahead and manually updated it, however it will break again on the next release.

https://github.com/axieum/authme/blob/a1f44fdfe3416483d2394f506a1a30e9b237e9b8/build.gradle#L217-L218

I wonder if Minotaur is preprocessing relative links in the markdown?

**Comment by axieum** [comment]
Minotaur mentions this:

> This does not occur with the `modrinth` task; you must use the `modrinthSyncBody` task separately to accomplish this.
